const TW = "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains";
const CG = "https://assets.coingecko.com/coins/images";

export interface StakingProduct {
  id: string;
  symbol: string;
  name: string;
  aprPct: number;
  durations: number[];
  defaultDuration: number;
  icon: string;
}

export const STAKING_VISIBLE_COUNT = 10;

export const NATIVE_STAKING_ID = "mva";

export const STAKING_PRODUCTS: StakingProduct[] = [
  {
    id: NATIVE_STAKING_ID,
    symbol: "MVA",
    name: "MVA Coin",
    aprPct: 12.6,
    durations: [7, 30, 90, 180],
    defaultDuration: 30,
    icon: "/images/mva-coin.png",
  },
  {
    id: "eth",
    symbol: "ETH",
    name: "Ethereum",
    aprPct: 1.26,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/ethereum/info/logo.png`,
  },
  {
    id: "dot",
    symbol: "DOT",
    name: "Polkadot",
    aprPct: 0.99,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/polkadot/info/logo.png`,
  },
  {
    id: "bnb",
    symbol: "BNB",
    name: "BNB",
    aprPct: 0.27,
    durations: [7, 90, 120],
    defaultDuration: 90,
    icon: `${TW}/smartchain/info/logo.png`,
  },
  {
    id: "avax",
    symbol: "AVAX",
    name: "Avalanche",
    aprPct: 4.32,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${TW}/avalanchec/info/logo.png`,
  },
  {
    id: "near",
    symbol: "NEAR",
    name: "NEAR Protocol",
    aprPct: 2.51,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/near/info/logo.png`,
  },
  {
    id: "apt",
    symbol: "APT",
    name: "Aptos",
    aprPct: 1.52,
    durations: [7, 14, 90],
    defaultDuration: 14,
    icon: `${TW}/aptos/info/logo.png`,
  },
  {
    id: "algo",
    symbol: "ALGO",
    name: "Algorand",
    aprPct: 2.52,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/algorand/info/logo.png`,
  },
  {
    id: "ada",
    symbol: "ADA",
    name: "Cardano",
    aprPct: 1.35,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${TW}/cardano/info/logo.png`,
  },
  {
    id: "sol",
    symbol: "SOL",
    name: "Solana",
    aprPct: 3.15,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/solana/info/logo.png`,
  },
  {
    id: "mina",
    symbol: "MINA",
    name: "Mina",
    aprPct: 2.43,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${CG}/10970/small/MINA.png`,
  },
  {
    id: "btc",
    symbol: "BTC",
    name: "Bitcoin",
    aprPct: 0.41,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/bitcoin/info/logo.png`,
  },
  {
    id: "matic",
    symbol: "POL",
    name: "Polygon",
    aprPct: 3.08,
    durations: [7, 30, 90],
    defaultDuration: 30,
    icon: `${TW}/polygon/info/logo.png`,
  },
  {
    id: "atom",
    symbol: "ATOM",
    name: "Cosmos",
    aprPct: 4.85,
    durations: [14, 90],
    defaultDuration: 90,
    icon: `${TW}/cosmos/info/logo.png`,
  },
  {
    id: "link",
    symbol: "LINK",
    name: "Chainlink",
    aprPct: 1.18,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/ethereum/assets/0x514910771AF9Ca656af840dff83E8264EcF986CA/logo.png`,
  },
  {
    id: "uni",
    symbol: "UNI",
    name: "Uniswap",
    aprPct: 2.04,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/logo.png`,
  },
  {
    id: "aave",
    symbol: "AAVE",
    name: "Aave",
    aprPct: 1.67,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${TW}/ethereum/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9/logo.png`,
  },
  {
    id: "op",
    symbol: "OP",
    name: "Optimism",
    aprPct: 2.22,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/optimism/info/logo.png`,
  },
  {
    id: "arb",
    symbol: "ARB",
    name: "Arbitrum",
    aprPct: 2.11,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${CG}/16547/small/photo_2023-03-29_21.47.00.jpeg`,
  },
  {
    id: "sui",
    symbol: "SUI",
    name: "Sui",
    aprPct: 3.64,
    durations: [7, 30, 90],
    defaultDuration: 30,
    icon: `${TW}/sui/info/logo.png`,
  },
  {
    id: "ton",
    symbol: "TON",
    name: "Toncoin",
    aprPct: 3.91,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${TW}/ton/info/logo.png`,
  },
  {
    id: "trx",
    symbol: "TRX",
    name: "TRON",
    aprPct: 4.12,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/tron/info/logo.png`,
  },
  {
    id: "xrp",
    symbol: "XRP",
    name: "XRP",
    aprPct: 0.88,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/ripple/info/logo.png`,
  },
  {
    id: "ltc",
    symbol: "LTC",
    name: "Litecoin",
    aprPct: 0.62,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/litecoin/info/logo.png`,
  },
  {
    id: "fil",
    symbol: "FIL",
    name: "Filecoin",
    aprPct: 5.14,
    durations: [14, 90, 120],
    defaultDuration: 90,
    icon: `${TW}/filecoin/info/logo.png`,
  },
  {
    id: "icp",
    symbol: "ICP",
    name: "Internet Computer",
    aprPct: 6.08,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${CG}/14495/small/Internet_Computer_logo.png`,
  },
  {
    id: "hbar",
    symbol: "HBAR",
    name: "Hedera",
    aprPct: 2.77,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/hedera/info/logo.png`,
  },
  {
    id: "inj",
    symbol: "INJ",
    name: "Injective",
    aprPct: 4.55,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${CG}/12882/small/Secondary_Symbol.png`,
  },
  {
    id: "sei",
    symbol: "SEI",
    name: "Sei",
    aprPct: 3.33,
    durations: [7, 30, 90],
    defaultDuration: 30,
    icon: `${CG}/28205/small/Sei_Logo_-_Transparent.png`,
  },
  {
    id: "tia",
    symbol: "TIA",
    name: "Celestia",
    aprPct: 5.72,
    durations: [14, 90],
    defaultDuration: 90,
    icon: `${CG}/31967/small/tia.jpg`,
  },
  {
    id: "ftm",
    symbol: "FTM",
    name: "Fantom",
    aprPct: 2.19,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/fantom/info/logo.png`,
  },
  {
    id: "crv",
    symbol: "CRV",
    name: "Curve",
    aprPct: 3.48,
    durations: [7, 90],
    defaultDuration: 90,
    icon: `${TW}/ethereum/assets/0xD533a949740bb3306d119CC777fa900bA034cd52/logo.png`,
  },
  {
    id: "mkr",
    symbol: "MKR",
    name: "Maker",
    aprPct: 1.09,
    durations: [7, 90],
    defaultDuration: 7,
    icon: `${TW}/ethereum/assets/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2/logo.png`,
  },
  {
    id: "atom2",
    symbol: "OSMO",
    name: "Osmosis",
    aprPct: 7.21,
    durations: [14, 90],
    defaultDuration: 14,
    icon: `${TW}/osmosis/info/logo.png`,
  },
  {
    id: "usdt",
    symbol: "USDT",
    name: "Tether",
    aprPct: 4.05,
    durations: [7, 30, 90],
    defaultDuration: 30,
    icon: `${TW}/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png`,
  },
  {
    id: "usdc",
    symbol: "USDC",
    name: "USD Coin",
    aprPct: 3.86,
    durations: [7, 30, 90],
    defaultDuration: 30,
    icon: `${CG}/6319/small/usdc.png`,
  },
];
